// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

// Provide a lazy factory for creating a browser Supabase client.
// Dynamic import prevents importing Node-only code at module evaluation time,
// which could surface in Edge/runtime contexts if this module is imported.
export async function createBrowserSupabaseClient() {
  if (typeof window === 'undefined') {
    throw new Error('createBrowserSupabaseClient() must be called in the browser')
  }

  const { createClient } = await import('@supabase/supabase-js')

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: window.localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  })
}

// Note: previously this module exported a top-level `supabase` instance.
// Callers should now `await createBrowserSupabaseClient()` in client-only code.